const DEFAULT_TITLE = "The AD-LVA Surgery";
const DEFAULT_DESCRIPTION = "Surgery for the AD-LVA";
const DEFAULT_BASE_URL = "https://www.ad-lva.com/";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "AD-LVA",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["AD-LVA", "Surgery", "AD-LVA Surgery"],
  DEFAULT_SITE_NAME: "AD-LVA Surgery",
  DEFAULT_BASE_URL: DEFAULT_BASE_URL,
  DEFAULT_PREVIEW_IMG: "/ogimage.png",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,

  DEFAULT_SOCIAL_MEDIA_MESSAGE: "Surgery for the AD-LVA",
};

export default CONSTANTS;
